name: TruffleHog OSS
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.86.1
             
